### PR TITLE
Use Correct tier0 on Linux || Use valid path to Tier0 on macos

### LINKED ISSUE #90: [BUG] Tier0 vs Tier0_client
**Describe the bug**
GmodDotNet uses `tier0`'s `Msg` function to log messages, but `tier0` is on windows, and `tier0`, `tier0_client` on non-windows

**To Reproduce**
use not windows gmod client/server

**Expected behavior**
uses `tier0_client`'s `Msg` on `CLIENT`, and `tier0`'s `Msg` on `SERVER`

**Platforms where you've faced the bug**
- [x] SRCDS Linux
- [ ] SRCDS Windows
- [ ] Garry's Mod Windows
- [x] Garry's Mod Linux
- [x] Garry's Mod macOS

**Additional context**
~~strange~~

### PR DESCRIPTION
**Pull request by SupinePandora43**
fixes #90

### CODE REVIEW

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 1]
```diff
@@ -13,9 +14,53 @@ internal class GameConsoleWriter : TextWriter
...
+            else if (OperatingSystem.IsLinux())
+            {
+                lua.PushSpecial(SPECIAL_TABLES.SPECIAL_GLOB);
+                lua.GetField(-1, "game");
+                lua.GetField(-1, "IsDedicated");
+                lua.MCall(0, 1);
+                bool is_dedicated = lua.GetBool(-1);
+                lua.Pop(1);
+
+                if (is_dedicated is true)
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: This new C# 9.0 syntax is fancy, but I would rather just write `if (is_dedicated)`.

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 2]
```diff
@@ -13,9 +14,53 @@ internal class GameConsoleWriter : TextWriter
...
+                Msg = Msg_Tier0;
+            }
+            else if (OperatingSystem.IsLinux())
+            {
+                lua.PushSpecial(SPECIAL_TABLES.SPECIAL_GLOB);
+                lua.GetField(-1, "game");
+                lua.GetField(-1, "IsDedicated");
+                lua.MCall(0, 1);
+                bool is_dedicated = lua.GetBool(-1);
+                lua.Pop(1);
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: Are you sure that there is only one item to pop from the stack? It seems like there are three objects: global table, game table, and bool value returned by IsDedicated. Note that `GetBool` does not pop values from the stack: [https://docs.gmodnet.xyz/api/GmodNET.API.ILua.html#GmodNET_API_ILua_GetBool_System_Int32_](https://docs.gmodnet.xyz/api/GmodNET.API.ILua.html#GmodNET_API_ILua_GetBool_System_Int32_)

**Review by GlebChili — DISMISSED** [review]

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs (hunk 1 above)
Comment (SupinePandora43) [reply gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: ~~every day we stay futher from god~~
yeah, i'm just using `is` and `is not` just too often.

**Comment by GlebChili** [comment]
@SupinePandora43 Looks fine. Need to test it manually before approving.

**Comment by GlebChili** [comment]
Manual test matrix:

- [x] macOS Client
- [x] Linux Client
- [x] Linux Server
- [x] Windows Client
- [x] Windows Server

**Comment by GlebChili** [comment]
@SupinePandora43 PR build is failing on MacOS:
```
System.DllNotFoundException: Unable to load shared library 'GarrysMod_Signed/Contents/MacOS/libtier0.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(GarrysMod_Signed/Contents/MacOS/libtier0.dylib, 1): image not found
   at GmodNET.GameConsoleWriter.Msg_Tier0_MacOS(String msg)
   at GmodNET.GameConsoleWriter.Write(String value) in /Users/admin/Documents/GitHub/GmodDotNet/gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:line 69
   at GmodNET.GameConsoleWriter.WriteLine(String value) in /Users/admin/Documents/GitHub/GmodDotNet/gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:line 100
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GmodNET.GlobalContext.LoadModule(ILua lua) in /Users/admin/Documents/GitHub/GmodDotNet/gm_dotnet_managed/GmodNET/GloabalContext.cs:line 101
```

Looking for fix.

**Comment by GlebChili** [comment]
@SupinePandora43 Linux server is failing:
```
System.EntryPointNotFoundException: Unable to find an entry point named 'Msg_Tier0' in shared library 'tier0'.
   at GmodNET.GameConsoleWriter.Msg_Tier0(String msg)
   at GmodNET.GameConsoleWriter.Write(String value) in /home/gleb/Code/GmodDotNet/gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:line 69
   at GmodNET.GameConsoleWriter.WriteLine(String value) in /home/gleb/Code/GmodDotNet/gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:line 100
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at GmodNET.GlobalContext.LoadModule(ILua lua) in /home/gleb/Code/GmodDotNet/gm_dotnet_managed/GmodNET/GloabalContext.cs:line 101

```

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 3]
```diff
@@ -13,9 +14,53 @@ internal class GameConsoleWriter : TextWriter
...
+
         [DllImport("tier0", CallingConvention = CallingConvention.Cdecl)]
-        private static extern void Msg([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
+        private static extern void Msg_Tier0([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
+
+        [DllImport("tier0_client", CallingConvention = CallingConvention.Cdecl)]
+        private static extern void Msg_Tier0_Client([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
+
+        [DllImport("GarrysMod_Signed/Contents/MacOS/libtier0.dylib", CallingConvention = CallingConvention.Cdecl)]
+        private static extern void Msg_Tier0_MacOS([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: We can't use DllImport on macOS due to the game app bundle structure. Here is an example of the fix which worked for me: https://gist.github.com/GlebChili/a6d14a7fc7f8970bd49a6b4573b5eacc

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 4]
```diff
@@ -13,9 +14,53 @@ internal class GameConsoleWriter : TextWriter
...
+                Msg = Msg_Tier0_MacOS;
+            }
+            else Msg = (string msg) => { throw new PlatformNotSupportedException(); };
+        }
+
+#pragma warning disable CA2101 // workaround for https://github.com/dotnet/roslyn-analyzers/issues/5009
+
         [DllImport("tier0", CallingConvention = CallingConvention.Cdecl)]
-        private static extern void Msg([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
+        private static extern void Msg_Tier0([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: This is not working. Since function is not called `Msg` anymore, you have to manually specify `EntryPoint` in DllImport: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.entrypoint?view=net-5.0

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 5]
```diff
@@ -13,9 +14,53 @@ internal class GameConsoleWriter : TextWriter
...
+
+        [DllImport("tier0_client", CallingConvention = CallingConvention.Cdecl)]
+        private static extern void Msg_Tier0_Client([MarshalAs(UnmanagedType.LPUTF8Str)] string msg);
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: Same as above, `EntryPoint` must be specified by hands.

**Review by GlebChili — CHANGES_REQUESTED** [review]
Please, test your PR next time, the EntryPoint issue could be spotted earlier.

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs (hunk 3 above)
Comment (SupinePandora43) [reply gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: whoa!
`delegate*` usage!

```cs
                    Msg = (message) =>
                    {
                        byte[] string_array = Encoding.UTF8.GetBytes(message);
                        fixed (byte* ptr = &string_array[0])
                        {
                            msg_func(ptr);
                        }
                    };
```
i probably can find a better solution for that.

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs (hunk 4 above)
Comment (SupinePandora43) [reply gm_dotnet_managed/GmodNET/GameConsoleWriter.cs]: totally forgot about it

File: gm_dotnet_managed/GmodNET/GameConsoleWriter.cs [hunk 6]
```diff
@@ -13,9 +14,103 @@ internal class GameConsoleWriter : TextWriter
...
+                        bool message__allocated = false;
+                        try
+                        {
+                            //
+                            // Marshal
+                            //
+                            if (message != null)
+                            {
+                                int message__bytelen = (message.Length + 1) * 3 + 1;
+                                if (message__bytelen > 260)
```
Comment (GlebChili) [inline gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:63]: Why do we want to stop at exactly 260 bytes for stack allocations?

Comment (SupinePandora43) [reply gm_dotnet_managed/GmodNET/GameConsoleWriter.cs:63]: that's `DllImportGenerator`'s threshold.

> In the built-in system, marshalling a string contains an optimization for parameters passed by value to allocate on the stack (instead of through AllocCoTaskMem) if the string is below a certain length (MAX_PATH)

**Review by GlebChili — APPROVED** [review]
